-- AlterTable
ALTER TABLE "site_content" ADD COLUMN     "aboutAgencyDescription" TEXT NOT NULL DEFAULT 'Fondee sur des valeurs de confiance et de transparence, notre agence place chaque client au centre de son action. Nous mettons notre connaissance du marche local au service de vos projets immobiliers, qu il s agisse d une premiere acquisition ou d un investissement stratégique.',
ADD COLUMN     "aboutHeroDescription" TEXT NOT NULL DEFAULT 'Idriss Villa Style combine expertise terrain, outils digitaux et accompagnement humain pour vous aider a vendre, acheter ou louer dans les meilleures conditions.',
ADD COLUMN     "aboutHeroTitle" TEXT NOT NULL DEFAULT 'Une agence immobiliere moderne, orientee resultat',
ADD COLUMN     "aboutMetric1Label" TEXT NOT NULL DEFAULT 'Biens verifies',
ADD COLUMN     "aboutMetric1Value" TEXT NOT NULL DEFAULT '500+',
ADD COLUMN     "aboutMetric2Label" TEXT NOT NULL DEFAULT 'Clients accompagnes',
ADD COLUMN     "aboutMetric2Value" TEXT NOT NULL DEFAULT '1000+',
ADD COLUMN     "aboutMetric3Label" TEXT NOT NULL DEFAULT 'Annees d experience',
ADD COLUMN     "aboutMetric3Value" TEXT NOT NULL DEFAULT '10+',
ADD COLUMN     "aboutMetric4Label" TEXT NOT NULL DEFAULT 'Satisfaction client',
ADD COLUMN     "aboutMetric4Value" TEXT NOT NULL DEFAULT '98%',
ALTER COLUMN "aboutAdminNote" SET DEFAULT 'Cette page A propos peut etre mise a jour depuis l espace Admin (contenu, chiffres et sections).',
ALTER COLUMN "contactHeaderTitle" SET DEFAULT 'Contactez-nous',
ALTER COLUMN "contactHeaderDescription" SET DEFAULT 'Notre equipe est a votre disposition pour repondre a toutes vos questions et vous accompagner dans votre projet immobilier.',
ALTER COLUMN "contactPhone" SET DEFAULT '+212 600 00 00 00',
ALTER COLUMN "contactEmail" SET DEFAULT 'contact@idrissvilla.com',
ALTER COLUMN "contactAddress" SET DEFAULT '123 Avenue Mohammed V, Tanger, Maroc',
ALTER COLUMN "contactHours" SET DEFAULT 'Lun - Ven: 9h00 - 18h00',
ALTER COLUMN "facebookUrl" SET DEFAULT 'https://facebook.com',
ALTER COLUMN "instagramUrl" SET DEFAULT 'https://instagram.com',
ALTER COLUMN "whatsappUrl" SET DEFAULT 'https://wa.me/212600000000';
